### PR TITLE
add draft version vantage point tree

### LINKED ISSUE #24: Vantage-point tree
A [vantage-point tree](https://en.wikipedia.org/wiki/Vantage-point_tree) would allow nearest neighbor search without requiring multidimensional points.

### PR DESCRIPTION
**Pull request by minshao**
A vantage point tree implementation with basic search nearest point function.

Closes #24

### CODE REVIEW

**Comment by msk** [comment]
Please expand your description and explain what part of #24 is completed in this PR and what are yet to be addressed.

**Comment by minshao** [comment]
> Please expand your description and explain what part of #24 is completed in this PR and what are yet to be addressed.

It completes what #24 asked, however, I don't really like the current design, I'd like to improve the Metric traits.

**Comment by msk** [comment]
> > Please expand your description and explain what part of #24 is completed in this PR and what are yet to be addressed.
> 
> It completes what #24 asked, however, I don't really like the current design, I'd like to improve the Metric traits.

Then let's close #24 and creates a new one for `Metric`.

**Review by msk — CHANGES_REQUESTED** [review]
Please update CHANGELOG.

**Review by msk — APPROVED** [review]

**Pull request merged**
